package tw.org.itri.smx.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12 Tue Feb 08 14:43:32 CST 2011 Generated source version: 2.2.12
 */

public final class Calculator_CalculatorImplPort_Client
{

    private static final QName SERVICE_NAME = new QName("http://ws.smx.itri.org.tw/", "CalculatorImplService");

    private Calculator_CalculatorImplPort_Client()
    {
    }

    public static void main(String args[]) throws Exception
    {
        URL wsdlURL = CalculatorImplService.WSDL_LOCATION;
        if (args.length > 0)
        {
            File wsdlFile = new File(args[0]);
            try
            {
                if (wsdlFile.exists())
                {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else
                {
                    wsdlURL = new URL(args[0]);
                }
            }
            catch (MalformedURLException e)
            {
                e.printStackTrace();
            }
        }

        CalculatorImplService ss = new CalculatorImplService(wsdlURL, SERVICE_NAME);
        Calculator port = ss.getCalculatorImplPort();

        {
            System.out.println("Invoking add...");
            int _add_arg0 = 1;
            int _add_arg1 = 1;
            int _add__return = port.add(_add_arg0, _add_arg1);
            System.out.println("add.result=" + _add__return);

        }

        System.exit(0);
    }

}
