package tw.org.itri.smx.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Tue Feb 08 14:43:32 CST 2011
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://ws.smx.itri.org.tw/", name = "Calculator")
@XmlSeeAlso({ObjectFactory.class})
public interface Calculator {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.smx.itri.org.tw/", className = "tw.org.itri.smx.ws.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.smx.itri.org.tw/", className = "tw.org.itri.smx.ws.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
